controllers/question_handler.py
from flask import render_template, request, redirect, Blueprint, session
from controllers import data_manager
import util

question = Blueprint('question', __name__, template_folder='templates')


@question.route("/question", methods=["POST", "GET"])
def add_question():
    util.check_if_user_is_logged()
    username, logged_user_id = util.get_user_details_from_session()
    default_blank_question = {}
    if request.method == "POST":
        new_question = set_question_values(default_blank_question)
        if not new_question["image"]:
            new_question["image"] = ''
        data_manager.add_record(new_question, "question")
        return redirect("/list")
    return render_template(
        "question_form.html",
        old_record=default_blank_question,
        is_new=True,
        user_id=logged_user_id,
        username=username
    )


@question.route("/question/<question_id>/edit", methods=["POST", "GET"])
def edit_question(question_id):
    util.check_if_user_is_logged()
    username, logged_user_id = util.get_user_details_from_session()
    selected_question = data_manager.get_specific_record(question_id, "question")
    util.check_if_user_is_owner(logged_user_id, selected_question["user_id"])
    if request.method == "POST":
        updated_question = set_question_values(selected_question)
        if not updated_question["image"]:
            updated_question["image"] = ''
        data_manager.edit_record(updated_question, "question")
        return redirect("/question/" + str(question_id))
    return render_template(
        "question_form.html",
        old_record=selected_question,
        is_new=False,
        user_id=logged_user_id,
        username=username
    )


@question.route("/question/<question_id>/delete")
def delete_question(question_id):
    util.check_if_user_is_logged()
    username, logged_user_id = util.get_user_details_from_session()
    selected_question = data_manager.get_specific_record(question_id, "question")
    util.check_if_user_is_owner(logged_user_id, selected_question["user_id"])
    all_answers = data_manager.get_all_records("answer")
    for answer in all_answers:
        if str(answer.get("question_id")) == str(question_id):
            data_manager.delete_record(answer.get("id"), "answer")
            data_manager.delete_connected_comment(-1, answer.get("id"))
    data_manager.delete_connected_comment(question_id, -1)
    data_manager.delete_connected_tags(question_id)
    data_manager.delete_record(question_id, "question")
    return redirect("/list")


def set_question_values(manipulated_question):
    manipulated_question["title"] = request.form["title"]
    manipulated_question["submission_time"] = util.get_new_timestamp()
    manipulated_question["message"] = request.form["description"]
    manipulated_question["user_id"] = data_manager.get_user_data(session['username'])['id']
    if 'file' in request.files:
        file = request.files['file']
        manipulated_question["image"] = util.save_image(file, data_manager.UPLOAD_FOLDER, "question")
    return manipulated_question

controllers/registration_handler.py
from flask import render_template, request, redirect, Blueprint, flash, session
import bcrypt
from controllers import data_manager
import util

registration = Blueprint('registration', __name__, template_folder='templates')


@registration.route("/login", methods=['GET', 'POST'])
def login():
    if 'username' in session:
        return redirect("/")
    if request.method == "GET":
        return render_template("login.html", logged=False)
    username = request.form.get("email")
    if not user_already_registered(username):
        flash('Wrong password or username!')
        return redirect("/login")
    password = request.form.get("password")
    if username and password:
        hashed_password = data_manager.get_user_data(username).get("password")
        if bcrypt.checkpw(password.encode("utf-8"), hashed_password.encode("utf-8")):
            session["username"] = username
            session["user_id"] = data_manager.get_user_data(username).get("id")
            return redirect("/")
    flash('Wrong password or username!')
    return redirect("/login")


def user_already_registered(email):
    for user in data_manager.get_all_users_emails():
        if user['email'] == email:
            return True
    return False


@registration.route("/registration", methods=['GET', 'POST'])
def register():
    if 'username' in session:
        return redirect("/")
    if request.method == "GET":
        return render_template("register.html", logged=False)
    if user_already_registered(request.form.get("email")):
        flash('User already registered !')
        return redirect("/registration")
    elif request.form.get("password") != request.form.get("cpassword"):
        flash('Passwords not matching - try again')
        return redirect("/registration")
    users_collection = {
        "email": request.form.get("email"),
        "password": bcrypt.hashpw(request.form.get("password").encode("utf-8"),
                                  bcrypt.gensalt(rounds=10)).decode("utf-8"),
        "registration_time": util.get_new_timestamp(), "reputation": 0}
    data_manager.add_user(users_collection)
    flash('Congratulations - you have registered successfully - you can now log in')
    return redirect("/login")


@registration.route("/logout")
def logout():
    if 'username' in session:
        session.pop('username', None)
    return redirect("/")

controllers/vote_handler.py
from flask import redirect, Blueprint, session, abort, render_template
from controllers import data_manager

vote = Blueprint('vote', __name__, template_folder='templates')


@vote.route("/question/<question_id>/<vote>")
def question_vote(question_id, vote):
    if 'username' not in session:
        abort(401)
    username = session['username']
    user_id = data_manager.get_user_data(username).get("id")
    user_votes = data_manager.get_user_votes(user_id)
    question = data_manager.get_specific_record(question_id, "question")
    if int(user_id) == int(question.get("user_id")):
        return render_your_question_page("question")
    for voter in user_votes:
        print(voter["question_id"])
        print(question_id)
        if voter["question_id"] and int(voter["question_id"]) == int(question_id) and int(user_id) == int(voter["user_id"]):
            return render_already_voted_page("question")
    if vote == "down":
        data_manager.update_vote_number("question", str(question_id), "down")
        data_manager.update_reputation(question["user_id"], -2)
    else:
        data_manager.update_vote_number("question", str(question_id), "up")
        data_manager.update_reputation(question["user_id"], 5)
    data_manager.update_question_vote(user_id, question_id)
    return redirect("/question/" + question_id)


@vote.route("/answer/<answer_id>/<voting_type>")
def answer_vote(answer_id, voting_type):
    if 'username' not in session:
        abort(401)
    username = session['username']
    user_id = data_manager.get_user_data(username).get("id")
    user_votes = data_manager.get_user_votes(user_id)
    answer = data_manager.get_specific_record(answer_id, "answer")
    if int(user_id) == int(answer.get("user_id")):
        return render_your_question_page("answer")
    for vote in user_votes:
        if vote["answer_id"] and int(vote["answer_id"]) == int(answer_id) and int(user_id) == int(vote["user_id"]):
            return render_already_voted_page("answer")
    if voting_type == "down":
        data_manager.update_vote_number("answer", str(answer_id), "down")
        data_manager.update_reputation(answer["user_id"], -2)
    else:
        data_manager.update_vote_number("answer", str(answer_id), "up")
        data_manager.update_reputation(answer["user_id"], 10)
    data_manager.update_answer_vote(user_id, answer_id)
    return redirect("/question/" + str(answer.get("question_id")))


def render_already_voted_page(option):
    username = session['username']
    user_id = session['user_id']
    return render_template(
        "error_page.html",
        error_code="",
        error_message="Already voted",
        message="You already voted on {}!".format(option),
        user_id=user_id,
        username=username
    )


def render_your_question_page(option):
    username = session['username']
    user_id = session['user_id']
    return render_template(
        "error_page.html",
        error_code="",
        error_message="This is your {}".format(option),
        message="",
        user_id=user_id,
        username=username
    )

templates/add_tag.html
{% extends "layout.html" %}
{% block title %}Tag Form{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>Add tag</h1>
                </div>
            </div>
            <div class="table-content">
                <div class="add_edit_form">
                    <h3>Select available tag...</h3>
                    <form class="flex-column-center-horizontally">
                        <select class="drop_down_btn" name="new_tag" id="new_tag">
                            {% for available_tag in tags_list %}
                                <option value="{{ available_tag.name }}">{{ available_tag.name }}</option>
                            {% endfor %}
                        </select>
                        <button class="drop_down_btn" type="submit">Submit</button>
                    </form>
                    <h3>...or add a new tag</h3>
                    <form class="flex-column-center-horizontally">
                        <input class="search-input drop_down_btn" id="new_tag" name="new_tag" type="text">
                        <button class="drop_down_btn" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/answer_form.html
{% extends "layout.html" %}
{% block title %}Answer Form{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>{{ "Add new answer" if is_new else "Edit your answer" }}</h1>
                </div>
            </div>
            <div class="table-content">
                <div class="add_edit_form">
                    <form class="flex-column-center-horizontally" id=answer_form
                          action={{ "/question/" + old_record.question_id|string + "/new-answer" if is_new else "/answer/" + old_record.id|string + "/edit" }} method="POST"
                          enctype="multipart/form-data">
                        <label for="description">Answer message:</label><br/>
                        <textarea class="text_input" id="description" name="description" rows="10"
                                  cols="100">{{ old_record.message|string }}</textarea><br/>
                        <label>Select image</label>
                        <input class="select_img" type="file" name="file" id="file">
                        <button class="drop_down_btn" type="submit">{{ "Add new answer" if is_new else "Edit your answer" }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/comment_form.html
{% extends "layout.html" %}
{% block title %}{{ "Edit " if comment else "New " }} Comment Form {% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1> {{ "Edit " if comment else "Add new " }} comment</h1>
                </div>
            </div>
                <div class="table-content">
                    <div class="add_edit_form">
                        <form class="flex-column-center-horizontally" id=comment_form
                            action="{% if comment %}
                                    {{ "/comment/" + comment.id|string + "/edit" }}
                                  {% else %}
                                    {{ "/answer/" + answer_id|string + "/new-comment" if answer_id else "/question/" + question_id|string + "/new-comment" }}
                                  {% endif %}"
                            method="POST">
                            <label for="description">Comment message:</label><br/>
                            <textarea class="text_input" id="description" name="message" rows="10"
                                  cols="100">{{ comment.message if comment }}</textarea><br/>
                            <button class="drop_down_btn" type="submit"> {{ "Edit " if comment else "Add new " }} comment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/error_page.html
{% extends "layout.html" %}
{% block title %}Error page{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>Error page</h1>
                </div>
            </div>
                <div class="table-content">
                    <div class="add_edit_form">
                        <div class="flex-column-center-horizontally">
                            <div class="error_code">{{ error_code }}</div>
                            <div class="error_message">{{ error_message }}</div>
                            <div class="error_message">{{ message }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style_new.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<header>
    <div class="search">
        <div class="table-search-form">
            <form action="/" methor="GET">
                {% if username %}
                    <a href="/user/{{ user_id }}" class="text">{{ username }}</a>
                    <a href="/logout" class="text">Logout</a>
                {% else %}
                    <a href="/login" class="text">Login</a>
                    <a href="/registration" class="text">Register</a>
                {% endif %}
                <input class="search-input drop_down_btn" id="search_phrase" name="search_phrase" type="text">
                <button class="search-button drop_down_btn" type="submit">Search</button>
            </form>
        </div>
    </div>
    <input type="checkbox" id="nav_toggle" class="nav_toggle">
    <nav>
        <ul>
            <li><a href="{{ url_for("homepage") }}">Home</a></li>
            <li><a href="{{ url_for("questions_list") }}">All questions</a></li>
            <li><a href="/tags">Tags</a></li>
            {% if username %}
                <li><a href="/users">All users</a></li>
            {% endif %}
        </ul>
    </nav>
    <label for="nav_toggle" class="nav_toggle_label">
        <span></span>
    </label>
</header>
<body class="body-styling">
{% block header %}{% endblock %}
{% block nav %}
    {% block nav_extension %}
    {% endblock %}
{% endblock %}
{% block body %}{% endblock %}
{% block footer %}
{% endblock %}
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
    {% block nav_extension %}
    {% endblock %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>Login</h1>
                </div>
            </div>
            <div class="table-content">
                <div class="add_edit_form">
                    <form class="flex-column-center-horizontally"
                          action="{{ url_for('registration.login') }}"
                          method="POST">
                        <label for="email">Email</label>
                        <input type="email" name= "email" id="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
                        <label for="password">Password</label>
                        <input input type="password" id="password" name="password" required>
{#                               pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"#}
{#                               title="Must contain at least one  number and one uppercase and lowercase letter,#}
{#                                and at least 8 or more characters">#}
                        <input type=submit value=Login>
                    </form>
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Question Form</title>
</head>
<body>
    <header>
        <h1>Please input new question</h1>
    </header>
    <form id=question_form action="/question" method="POST">
        <label for="title">Question title:</label><br/>
        <input id="title" name="title" type="text" value=""><br/>
        <label for="description">Question message:</label><br/>
        <textarea id="description" name="description" rows="4" cols="50"></textarea><br/>
        <label for="image">Select image:</label><br/>
        <input id="image" name="image" type="text" value=""><br/>
        <button type="submit">Add new question</button>
    </form>
</body>
</html>

templates/question_list.html
{% extends "layout.html" %}
{% block title %}Homepage{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
    {% block nav_extension %}
    {% endblock %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>{{ "Homepage" if is_homepage else "All questions" }}</h1>
                </div>
                <div class="table-header">
                    <div class="table-sorting-form">
                        <form action="{{ url_for('questions_list', sort_by=sort_by) }}">
                            <select class="drop_down_btn" name="sort_by" id="sort_by">
                                {% set sort_criteria = ["submission_time", "view_number", "vote_number", "title", "message"] %}
                                {% for sort_by_option in sort_criteria %}
                                    {% set sort_order = ['ASC', 'DESC'] %}
                                    {% for order in sort_order %}
                                        <option value="{{ sort_by_option }}-{{ order }}">sort by: {{ sort_by_option }}
                                            {% if order=='ASC' %} &#8595 {% else %} &#8593{% endif %}</option>
                                    {% endfor %}
                                {% endfor %}
                            </select>
                            <button class="drop_down_btn" type="submit">Sort</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="button-panel">
                {% if is_homepage or username == None %}
                    <a href="{{ url_for("questions_list") }}" class="nav_button">All Questions</a>
                {% else %}
                    <a href="{{ url_for("question.add_question") }}" class="nav_button">Ask new question</a>
                {% endif %}
            </div>
            {% for question in all_questions %}
                <div class="table-content">
                    <div class="table-details-and-description">
                        <div class="table-record-details">
                            <div class="answers-number">
                                <div class="answers-number-value">
                                    {{ question.get("number_of_answers") }}
                                </div>
                                <div class="answers-number-text">
                                    Answers
                                </div>
                            </div>
                            <div class="view-vote-numbers">
                                <div class="view-number">
                                    <div class="view-number-value">
                                        {{ question.get("view_number") }}
                                    </div>
                                    <div class="view-number-text">
                                        Views
                                    </div>
                                </div>
                                <div class="vote-number">
                                    <div class="vote-number-value">
                                        {{ question.get("vote_number") }}
                                    </div>
                                    <div class="vote-number-text">
                                        Votes
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-record-description">
                            <div class="question-title">
                                <a href="{{ url_for("show_question", question_id=question.get("id")|string) }}">{{ question.get("title") }}</a>
                            </div>
                            <div class="question-message">
                                {{ question.get("message") }}
                            </div>
                        </div>
                    </div>
                    <div class="table-record-actions-panel">
                        <div class="head-of-actions-panel">
                            USER ICON
                        </div>
                        {% if question.get("user_id") != user_id and username != None %}
                            <div class="vote-section">
                                <a href="{{ url_for("vote.question_vote", question_id=question.get("id")|string, vote="up") }}"
                                   methods="POST">
                                    <img src="{{ url_for('static', filename="icons/like_up.png") }}" width="50px"
                                         height="50px"
                                         alt="vote_up">
                                </a>
                                <a href="{{ url_for("vote.question_vote", question_id=question.get("id")|string, vote="down") }}"
                                   methods="POST">
                                    <img src="{{ url_for('static', filename="icons/like_down.png") }}" width="50px"
                                         height="50px"
                                         alt="vote_down">
                                </a>
                            </div>
                        {% endif %}
                        <div class="submission-time">
                            <div class="submission-time-text">
                                Update time:
                            </div>
                            <div class="submission-time-value">
                                {{ question.get("submission_time") }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/register.html
{% extends "layout.html" %}
{% block title %}Registration{% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
    {% block nav_extension %}
    {% endblock %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>Register</h1>
                </div>
            </div>
            <div class="table-content">
                <div class="add_edit_form">
                    <form class="flex-column-center-horizontally"
                          action="{{ url_for('registration.register') }}"
                          method="POST">
                        <label for="email">Email</label>
                        <input type="email" name= "email" id="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
                        <label for="password">Password</label>
                        <input input type="password" id="password" name="password" required>
{#                               pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"#}
{#                               title="Must contain at least one  number and one uppercase and lowercase letter,#}
{#                                and at least 8 or more characters">#}
                        <label for="cpassword">Confirm password</label>
                        <input input type="password" id="cpassword" name="cpassword" required>
                        <input type=submit value=Register>
                    </form>

                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}{{ super() }}{% endblock %}

templates/tags_list.html
{% extends "layout.html" %}
{% block title %} Tags {% endblock %}
{% block header %}
{% endblock %}
{% block nav %}
    {{ super() }}
    {% block nav_extension %}
    {% endblock %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="table">
            <div class="table-header-and-title">
                <div class="table-title">
                    <h1>Tags</h1>
                </div>
            </div>
        </div>
        {% for tag in tags %}
            <div class="table-content table-record-details">
                <div class="tags-name tags-background">
                    #{{ tag.name }} - total {{ tag.amount_of_question }} with this tag
                </div>
            </div>
            {% for question in tag.questions %}
                <div class="table-content">
                    <div class="table-details-and-description">
                        <div class="table-record-details">
                            <div class="answers-number">
                                <div class="answers-number-value">
                                    {{ question.get("number_of_answers") }}
                                </div>
                                <div class="answers-number-text">
                                    Answers
                                </div>
                            </div>
                            <div class="view-vote-numbers">
                                <div class="view-number">
                                    <div class="view-number-value">
                                        {{ question.get("view_number") }}
                                    </div>
                                    <div class="view-number-text">
                                        Views
                                    </div>
                                </div>
                                <div class="vote-number">
                                    <div class="vote-number-value">
                                        {{ question.get("vote_number") }}
                                    </div>
                                    <div class="vote-number-text">
                                        Votes
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-record-description">
                            <div class="question-title">
                                <a href="{{ url_for("show_question", question_id=question.get("question_id")|string) }}">{{ question.get("title") }}</a>
                            </div>
                            <div class="question-message">
                                {{ question.get("message") }}
                            </div>
                        </div>
                    </div>
                    <div class="table-record-actions-panel">
                        <div class="head-of-actions-panel">
                            USER ICON
                        </div>
                        {% if question.get("user_id") != user_id and username != None %}
                            <div class="vote-section">
                                <a href="{{ url_for("vote.question_vote", question_id=question.get("question_id")|string, vote="up") }}"
                                   methods="POST">
                                    <img src="{{ url_for('static', filename="icons/like_up.png") }}"
                                         width="50px"
                                         height="50px"
                                         alt="vote_up">
                                </a>
                                <a href="{{ url_for("vote.question_vote", question_id=question.get("question_id")|string, vote="down") }}"
                                   methods="POST">
                                    <img src="{{ url_for('static', filename="icons/like_down.png") }}"
                                         width="50px"
                                         height="50px"
                                         alt="vote_down">
                                </a>
                            </div>
                        {% endif %}
                        <div class="submission-time">
                            <div class="submission-time-text">
                                Update time:
                            </div>
                            <div class="submission-time-value">
                                {{ question.get("submission_time") }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}